# Generated by Django 5.0.4 on 2024-05-21 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('users', '0003_user_book_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
    ]
