# Generated by Django 5.0.4 on 2024-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('author', models.ManyToManyField(to='authors.author')),
                ('genre', models.ManyToManyField(to='genres.genre')),
            ],
        ),
    ]
